export const CARD_INFO = [
  { image: '/cards/card-1.webp', name: 'Messi' },
  { image: '/cards/card-2.webp', name: 'Roque' },
  { image: '/cards/card-3.webp', name: 'Telmo' },
  { image: '/cards/card-4.webp', name: 'Román' },
  { image: '/cards/card-5.webp', name: 'Anxo' },
  { image: '/cards/card-6.webp', name: 'Teo' },
  { image: '/cards/card-7.webp', name: 'Tía Dalva' },
  { image: '/cards/card-8.webp', name: 'Tío Diego' },
  { image: '/cards/card-9.webp', name: 'Mamá' },
  { image: '/cards/card-10.webp', name: 'Maradona' },
  { image: '/cards/card-11.webp', name: 'Papá' },
  { image: '/cards/card-12.webp', name: 'Abuela' },
  { image: '/cards/card-13.webp', name: 'Abuelo' },
  { image: '/cards/card-14.webp', name: 'Tía Bea' },
  { image: '/cards/card-15.webp', name: 'Tío Fede' },
  { image: '/cards/card-16.webp', name: 'Roque en bicicleta' },
  { image: '/cards/card-17.webp', name: 'Telmo rockero' },
  { image: '/cards/card-18.webp', name: 'Román con paraguas' },
  { image: '/cards/card-19.webp', name: 'Roque con saxo' },
  { image: '/cards/card-20.webp', name: 'Telmo de fútbol base' },
  { image: '/cards/card-21.webp', name: 'Román en bicicleta' },
  { image: '/cards/card-22.webp', name: 'Tristón' },
  { image: '/cards/card-23.webp', name: 'Peluche de Telmo' },
  { image: '/cards/card-24.webp', name: 'Tito' },
  { image: '/cards/card-25.webp', name: 'Leymita' },
  { image: '/cards/card-26.webp', name: 'Avispa velutina' },
  { image: '/cards/card-27.webp', name: 'Moscaa' },
  { image: '/cards/card-28.webp', name: 'Meme provisional' },
  { image: '/cards/card-29.webp', name: 'La mano de Dios provisional' },
  { image: '/cards/card-30.webp', name: 'Mate' }
]
