export const CARD_INFO = [
  { image: '/cards/card-1.webp', name: 'Messi' },
  { image: '/cards/card-2.webp', name: 'Roque' },
  { image: '/cards/card-3.webp', name: 'Telmo' },
  { image: '/cards/card-4.webp', name: 'Román' },
  { image: '/cards/card-5.webp', name: 'Anxo' },
  { image: '/cards/card-6.webp', name: 'Teo' },
  { image: '/cards/card-7.webp', name: 'Tía Dalva', translationKey: 'auntDalva' },
  { image: '/cards/card-8.webp', name: 'Tío Diego', translationKey: 'uncleDiego' },
  { image: '/cards/card-9.webp', name: 'Mamá', translationKey: 'mom' },
  { image: '/cards/card-10.webp', name: 'Maradona' },
  { image: '/cards/card-11.webp', name: 'Papá', translationKey: 'dad' },
  { image: '/cards/card-12.webp', name: 'Abuela', translationKey: 'grandma' },
  { image: '/cards/card-13.webp', name: 'Abuelo', translationKey: 'grandpa' },
  { image: '/cards/card-14.webp', name: 'Tía Bea', translationKey: 'auntBea' },
  { image: '/cards/card-15.webp', name: 'Tío Fede', translationKey: 'uncleFede' },
  { image: '/cards/card-16.webp', name: 'Roque en bicicleta', translationKey: 'roqueBike' },
  { image: '/cards/card-17.webp', name: 'Telmo rockero', translationKey: 'telmoRock' },
  { image: '/cards/card-18.webp', name: 'Román con paraguas', translationKey: 'romanUmbrella' },
  { image: '/cards/card-19.webp', name: 'Roque con saxo', translationKey: 'roqueSax' },
  { image: '/cards/card-20.webp', name: 'Telmo de fútbol base', translationKey: 'telmoFootball' },
  { image: '/cards/card-21.webp', name: 'Román en bicicleta', translationKey: 'romanBike' },
  { image: '/cards/card-22.webp', name: 'Tristón' },
  { image: '/cards/card-23.webp', name: 'Peluche de Telmo', translationKey: 'telmoBear' },
  { image: '/cards/card-24.webp', name: 'Tito' },
  { image: '/cards/card-25.webp', name: 'Leymita' },
  { image: '/cards/card-26.webp', name: 'Avispa velutina', translationKey: 'wasp' },
  { image: '/cards/card-27.webp', name: 'Mosca', translationKey: 'fly' },
  { image: '/cards/card-28.webp', name: 'Escudo del Depor', translationKey: 'deporShield' },
  { image: '/cards/card-29.webp', name: 'Yogurt de mosca', translationKey: 'flyYogurt' },
  { image: '/cards/card-30.webp', name: 'Mate' },
  { image: '/cards/card-31.webp', name: 'Roque, Telmo y Román', translationKey: 'threeKids' },
  { image: '/cards/card-32.webp', name: 'Árbol de los niños', translationKey: 'tree' },
  { image: '/cards/card-33.webp', name: 'Matamoscas', translationKey: 'flyswatter' }
]
